openapi: 3.0.0
info:
  title: Tropipay API
  version: '1.0'
  contact:
    name: Tropipay Team
    url: www.tropipay.com
    email: soporte@tropipay.com
  termsOfService: 'https://tropipay.com/terms'
  license:
    name: Tropipay - 2020 - All Right Reserved
  description: ''
servers:
  - description: Develop
    url: 'https://tropipay-dev.herokuapp.com/api'
paths:
  /access/login:
    post:
      summary: Getting API Token
      operationId: post-access-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                OK:
                  value:
                    user:
                      id: c01af560-c7f4-11e8-849a-1196b4225et9
                      name: John
                      surname: Doe
                      company: My Home
                      email: my@email.com
                      phone: '5555555555'
                      address: 'Catalunia Plaza, Barcelona'
                      walletId: null
                      t_c_version: /terms/v0.0
                      role: user
                      nationality: null
                      state: 1
                      balance: 923412
                      birthDate: '1986-02-03T23:00:00.000Z'
                      countryDestinationId: 1
                      city: Barcelona
                      postalCode: 8013
                      kycLevel: 3
                      occupationId: 6
                      clientTypeId: 1
                      isPublicOffice: false
                      birthCountryId: 0
                      province: Barcelona
                      groupId: 2
                      lastLogin: '2020-03-26T15:27:11.148Z'
                      pendingIn: -41380
                      pendingOut: 0
                      lang: es
                      shortId: YO6S
                      createdAt: '2018-10-04T16:44:24.380Z'
                      updatedAt: '2020-03-26T15:27:11.151Z'
                      group:
                        id: 2
                        name: SUPPORT
                        createdAt: '2020-03-16T15:31:48.232Z'
                        updatedAt: '2020-03-16T15:31:48.232Z'
                        permissions:
                          - id: 1
                            name: ALLOW_EXTERNAL_CHARGE
                            label: payments
                            createdAt: '2019-10-29T12:19:50.939Z'
                            updatedAt: '2019-10-29T12:19:50.939Z'
                            GroupPermission:
                              createdAt: '2020-03-16T15:31:48.278Z'
                              updatedAt: '2020-03-16T15:31:48.278Z'
                              groupId: 2
                              permissionId: 1
                          - id: 2
                            name: UPLOAD_DOCUMENT
                            label: support
                            createdAt: '2020-03-16T15:31:48.232Z'
                            updatedAt: '2020-03-16T15:31:48.232Z'
                            GroupPermission:
                              createdAt: '2020-03-16T15:31:48.278Z'
                              updatedAt: '2020-03-16T15:31:48.278Z'
                              groupId: 2
                              permissionId: 2
                      validAirbnb: true
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwMWFmNTYwLWM3ZjQtMTFlOC04NDlhLTExOTZiNDIyNWUyOSIsIm5hbWUiOiJSdWJlbiIsImVtYWlsIjoicnViZW4ubGhAZ21haWwuY29tIiwic3VybmFtZSI6IkxhbmcgSGVycmVyYSIsImNvbXBhbnkiOiJNaSBjYXNhIiwicGhvbmUiOiIzNDY1NDI5MTQ0NyIsInJvbGUiOiJhZG1pbiIsInN0YXRlIjoxLCJpYXQiOjE1ODUyMzY0MzEsImV4cCI6MTU4NTMyMjgzMX0.lrNYwUr2ysoLeaD68WLw86ztz_hJYm9ZrhiWLVPf-Uw
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                KO:
                  value:
                    error:
                      message:
                        code: 8
                        msg: 'Wrong username or password!'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              Getting Token:
                value:
                  email: user@email.com
                  password: userP4SSW00rd
        description: Authentication
      tags:
        - Authentication
  /paymentcards:
    get:
      summary: Get Payment Link List
      tags: []
      responses: {}
      operationId: get-sd
    parameters: []
    post:
      summary: Creating a Payment Link
      operationId: post-paymentcards
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Response OK Example:
                  value:
                    id: 94790650-f5a1-11e9-a5b8-8db2d78a55d6
                    reference: 23u4cgvz8k23djl85
                    concept: Gif Card - Experiencia culinaria.
                    description: Taxi + Experiencia
                    amount: 14000
                    currency: EUR
                    singleUse: false
                    reasonId: 1
                    userId: 6b16b480-47df-11e9-8b02-d75764f7c812
                    state: 1
                    updatedAt: '2019-10-23T14:29:54.628Z'
                    createdAt: '2019-10-23T14:29:54.102Z'
                    qrImage: 'data:image/png;base64,iVBORw0KG {...} XoGCsAAAAABJRU5ErkJggg=='
                    shortUrl: 'http://bit.ly/2WbaJKS'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Invalid Token Example:
                  value:
                    error:
                      msg: 'Failed to authenticate token!'
                      code: 934
      tags:
        - Payment Link
      description: "Charge to your clients or receive a remitance to your account by charge credits cards. \n\nYou will get a short URL and a QR code with the Payment Link "
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reference:
                  type: string
                  description: reference in your system
                concept:
                  type: string
                  description: ''
                description:
                  type: string
                amount:
                  type: integer
                  description: Cents
                currency:
                  type: string
                  description: 'EUR,USD (ISO)'
                singleUse:
                  type: boolean
                  description: true - payment link is closed after use it
                reasonId:
                  type: integer
                  description: See reasson list section for details
                expirationDays:
                  type: integer
                  description: How many days you allow order cancelation
                lang:
                  type: string
                  description: 'Link Payment Language (es,en,pt)'
                urlSuccess:
                  type: string
                  description: OK response redirect to this URL
                urlFailed:
                  type: string
                  description: KO response redirect to this URL
                urlNotification:
                  type: string
                  description: Callback notification with the response data
              required:
                - reference
                - concept
                - description
                - amount
                - currency
                - singleUse
                - reasonId
            examples:
              Creating a Recurrent Payment Link:
                value:
                  reference: your-own-system-reference
                  concept: test
                  description: test
                  amount: 100000
                  currency: EUR
                  singleUse: false
                  reasonId: 2
                  expirationDays: 1
                  lang: es
                  urlSuccess: 'https://mi-negocio.com/pago-ok'
                  urlFailed: 'https://mi-negocio.com/pago-ko'
                  urlNotification: 'https://mi-negocio.com/notificacion-pago'
        description: ''
      parameters:
        - schema:
            type: string
          in: header
          description: 'Bearer {your-token}'
          name: Authorization
          required: true
components:
  schemas: {}
