openapi: 3.0.0
info:
  title: TPP API v2.0
  version: '2.0'
  description: Tropipay API V2.0
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the infromation of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /api/v2/hook:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: |-
            Here we have an example of a valid response for a merchant who subscribed to two events:
            ```json
            [
                {
                    "event": "user_signup",
                    "target": "email",
                    "value": "tonykssa@gmail.com",
                    "createdAt": "2021-02-13T21:30:59.154Z",
                    "updatedAt": "2021-02-13T21:30:59.154Z"
                },
                {
                    "event": "user_login",
                    "target": "web",
                    "value": "http://localhost:4000/api/user/login/listen",
                    "createdAt": "2021-02-13T22:43:11.243Z",
                    "updatedAt": "2021-02-13T22:43:11.243Z"
                }
            ]
            ```
        '500':
          description: |-
            In case of error in the token encoding you will receive an internal error with a structure as shown below: 
            ```json
            {
                "error": {
                    "code": "InvalidCharacterError: Invalid character: the string to be decoded is not correctly encoded.",
                    "message": "Failed to authenticate token for Merchant!"
                }
            }
            ```
            In case of an error in the token keys or attempted security breach with the correct encoding, you will receive an internal error with a structure as shown below: 
            ```json
            {
                "error": {
                    "code": "OperationError: Failed to validate merchant token!",
                    "message": "Failed to authenticate token for Merchant!"
                }
            }
            ```
      operationId: get-api-v2-hook
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: ' Bearer Base64( API_CODE : API_KEY )'
      description: |
        Endpoint for get event list hook by merchant. 

        ## Authentication
        Fot the authentication you need to send the Authorization header with the value: 
        ```
          Bearer Base64( API_CODE : API_KEY )
        ```
        an example would be:
        ```
          Bearer MTplMXczeTRydzVlcjNvNGY0azRjOHI3dHY0NXY=
        ```
        Where you must calculate the token by using a Base64 of your **API_CODE + " : " + API_KEY** including the colom symbol ( : )

        ## Event 
        Events are made up of an object with three fundamental properties *(event, target, value)*
        ```json
        {
              "event": "user_signup",
              "target": "email",
              "value": "tonykssa@gmail.com",
              "createdAt": "2021-02-13T21:30:59.154Z",
              "updatedAt": "2021-02-13T21:30:59.154Z"
        }
        ```

        * **event:** String that represents the name of the event, you must select from the list of available events, otherwise it will not produce an error but it will not be executed. For get full list of available events see endpoint **GET /api/v2/hook/events**.
        * **target:** String representing the type of event supported. It is currently available: 'web' (allows to receive information in a url), 'email' (allows to receive information in an email address). 
        * **value:** String that represents the value depending on the type of selected event determined by the 'target' property, for example if the selected 'target' is email the value would be an email address, likewise if the selected 'target' is 'web' the expected value corresponds to a url that receives information through the HTTP POST method. 
    post:
      summary: ''
      operationId: post-api-v2-hook
      responses:
        '200':
          description: OK
      description: |
        Endpoint allows a merchant to subscribe to an event, specifying the options to receive information at the time it is trigger.

        ## Event 
        Events are made up of an object with three fundamental properties *(event, target, value)*

        * **event:** String that represents the name of the event, you must select from the list of available events, otherwise it will not produce an error but it will not be executed. For get full list of available events see endpoint **GET /api/v2/hook/events**.
        * **target:** String representing the type of event supported. It is currently available: 'web' (allows to receive information in a url), 'email' (allows to receive information in an email address). 
        * **value:** String that represents the value depending on the type of selected event determined by the 'target' property, for example if the selected 'target' is email the value would be an email address, likewise if the selected 'target' is 'web' the expected value corresponds to a url that receives information through the HTTP POST method. 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
        description: |-
          Here we have an example of a valid params request:
          ```json
          {
                "event": "user_signup",
                "target": "web",
                "value": "https://www.merchant_domain.com/api/user/signup/listen"
          }
          ```
components:
  schemas:
    User:
      title: User
      type: object
      description: User Model for Tropipay Clients
      x-examples:
        Alice Smith:
          id: 1423
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
